### ISSUE TITLE
mongo

### ISSUE THREAD

**Issue by KubaK1P** [1p22geo/kosmetyczk_kacper_dygon#1]
Czy pan kacper byłby w stanie wytłumaczyć mi baze mongo, bo widzę że ładnie to tu wszystko zaimplementowane?

**Comment by 1p22geo** [comment]
`git blame` pokazuje kto co zrobił w którym pliku.

Kacper robił frontend, od bazy jestem ja

**Comment by 1p22geo** [comment]
Wytłumaczyć mongodb to ci mogę na religii
